call compile preprocessFileLineNumbers "ui\builderActions.sqf";
call compile preprocessFileLineNumbers "ui\utilityActions.sqf";
call compile preprocessFileLineNumbers "ui\teleportActions.sqf";
call compile preprocessFileLineNumbers "ui\playerActions.sqf";
call compile preprocessFileLineNumbers "ui\resupplyActions.sqf";
call compile preprocessFileLineNumbers "ui\infoActions.sqf";
call compile preprocessFileLineNumbers "clientlogic\uidTraits.sqf";
call compile preprocessFileLineNumbers "clientlogic\restoreStartpos.sqf";
call compile preprocessFileLineNumbers "clientlogic\playerHandlers.sqf";
call compile preprocessFileLineNumbers "clientlogic\clientThreads.sqf";
[] call (missionNamespace getVariable "ui_bindKeys");
[] call (missionNamespace getVariable "ui_bind6Key");
[] call (missionNamespace getVariable "ui_bindTeleportKey");
[] call (missionNamespace getVariable "ui_bindKey5");
[] call (missionNamespace getVariable "ui_bind6Key_radioOnly");
[player] call (missionNamespace getVariable "fnc_applyUIDTraits");
[] call (missionNamespace getVariable "fnc_restoreStartPos");
[player] call (missionNamespace getVariable "fnc_setupPlayerHandlers");
player enableFatigue false;
[] call (missionNamespace getVariable "fnc_initInfoAndVehicleLock");
