call compileFinal preprocessFileLineNumbers "serverlogic\vehicles\vehicleInit.sqf";
call compileFinal preprocessFileLineNumbers "serverlogic\vehicles\initializeVeh.sqf";
call compileFinal preprocessFileLineNumbers "arealogic\createAreas.sqf";
call compileFinal preprocessFileLineNumbers "arealogic\createObjectives.sqf";
call compileFinal preprocessFileLineNumbers "arealogic\createAttacks.sqf";
call compileFinal preprocessFileLineNumbers "arealogic\createTasks.sqf";
call compileFinal preprocessFileLineNumbers "arealogic\preventHangup.sqf";
call compileFinal preprocessFileLineNumbers "serverlogic\functions.sqf";
call compileFinal preprocessFileLineNumbers "serverlogic\targetAir.sqf";
call compileFinal preprocessFileLineNumbers "serverlogic\spotServer.sqf";
call compileFinal preprocessFileLineNumbers "serverlogic\buildServer.sqf";
call compileFinal preprocessFileLineNumbers "serverlogic\crateServer.sqf";
call compileFinal preprocessFileLineNumbers "serverlogic\teleportServer.sqf";
call compileFinal preprocessFileLineNumbers "serverlogic\intelServer.sqf";
call compileFinal preprocessFileLineNumbers "serverlogic\handleServer.sqf";
call compileFinal preprocessFileLineNumbers "serverlogic\resupply\resupplyBase.sqf";
call compileFinal preprocessFileLineNumbers "serverlogic\resupply\resupplySupport.sqf";
call compileFinal preprocessFileLineNumbers "serverlogic\resupply\resupplyTriggers.sqf";
private _res = missionNamespace getVariable ["trackedVehicles", []];
[_res] call (missionNamespace getVariable "fnc_initVehicleSet");
[] call (missionNamespace getVariable "fnc_monitorVehicleRespawns");
[] call (missionNamespace getVariable "fnc_startZoneLogicThread");
[] call (missionNamespace getVariable "fnc_unitStartup");
